services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    Pimcore\Bundle\StudioExampleBundle\Installer:
        public: true

    Pimcore\Bundle\StudioExampleBundle\EventSubscriber\CustomTreeStyleSubscriber: ~

    Pimcore\Bundle\StudioExampleBundle\EventSubscriber\CustomAssetStyleSubscriber: ~

    Pimcore\Bundle\StudioExampleBundle\Webpack\WebpackEntryPointProvider:
        tags:
            - { name: pimcore_studio_ui.webpack_entry_point_provider }
            - { name: pimcore_studio_ui.webpack_entry_point_provider.document_editor_iframe }

    Pimcore\Bundle\StudioExampleBundle\Gdpr\MyDataProvider:
        tags:
            - { name: pimcore.studio_backend.gdpr_data_provider }

    Pimcore\Bundle\StudioExampleBundle\Grid\Column\Definition\SimpleTextDefinition:
        tags:
            - { name: pimcore.studio_backend.grid_column_definition }

    Pimcore\Bundle\StudioExampleBundle\Grid\Column\Definition\ProgressBarDefinition:
        tags:
            - { name: pimcore.studio_backend.grid_column_definition }

    Pimcore\Bundle\StudioExampleBundle\Grid\Column\Resolver\ProgressBarResolver:
        tags:
            - { name: pimcore.studio_backend.grid_column_resolver }

    Pimcore\Bundle\StudioExampleBundle\Grid\Column\Collector\ProgressBarCollector:
        tags:
            - { name: pimcore.studio_backend.grid_column_collector }
